version: "1"

project:
  name: u4s-chat
  description: "U4S — чат-помощник (YandexGPT + Vector Store), FastAPI на Amvera"

services:
  api:
    runtime: docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000
    env:
      AMVERA_API_URL: ${AMVERA_API_URL}
      AMVERA_MODEL: ${AMVERA_MODEL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    secrets:
      - AMVERA_API_TOKEN
    healthcheck:
      path: /health
      interval: 15s
      timeout: 3s
      retries: 3
    resources:
      cpu: "0.5"
      memory: "512Mi"
    domains:
      - host: ai-chatbot-u4s-karinausadba.amvera.io
        paths:
          - path: /
            port: 8000
            protocol: http

secrets:
  - name: AMVERA_API_TOKEN

